### ISSUE TITLE
Installing CN in xcat docker container, there was not computes.log

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-docker#10]
Installing CN in xcat docker container, there was not ``computes.log`` under ``/var/log/xcat``.

```
[root@c910f04x30v02 xcat]# ll
total 76
-rw------- 1 root root 16122 Apr  4 07:40 cluster.log
-rw------- 1 root root 57897 Apr  4 07:40 commands.log
drwxr-xr-x 2 root root     6 Apr  4 07:33 dump
drwx------ 2 root root     6 Apr  4 07:33 rflash
```

**Comment by robin2008** [comment]
As now using `host` network mode,  the rsyslog in container might not work as the rsyslog on docker host is running.

If using bridge mode,  then container will have a dedicate IP, then no port conflicts. But bridge mode needs to change docker host networking, wrong network configuration might cause the docker host lost connection.

We can check out if the new mode: macvlan could meet our requirements.


@hu-weihua Could you check with below workaround?
- stop rsyslog docker host
- stop and start the xcat container again
- exec into the container, restart rsyslog service

And provision CN again.

**Comment by hu-weihua** [comment]
When the provision process can work correctly, got ``compute.log``.

```
[root@c910f03c09k03 xcat]# ll
total 12576
-rw------- 1 root root 1194197 Apr 13 05:33 cluster.log
-rw------- 1 root root 9500654 Apr 13 05:33 commands.log
-rw------- 1 root root 2178903 Apr 13 05:21 computes.log
drwxr-xr-x 2 root root       6 Apr 12 10:16 dump
drwx------ 2 root root       6 Apr 12 10:16 rflash
```
So it seems the bug is not valid.  close this one.
