### ISSUE TITLE
New xCAT docker instance fails to read database.

### ISSUE THREAD

**Issue by DataSenseiAryan** [xcat2/xcat-docker#21]
I am able to PXE boot a machine in my cluster. I have mounted volumes as given in the documentation. I am using Postgressql database. The problem arises when I kill the current docker instance and then create a new instance. In the newly created instance xcat serve fails and gives error "Unable to open socket connection to xcatd daemon on localhost:3001.
Verify that the xcatd daemon is running and that your SSL setup is correct.
Connection failure: IO::Socket::INET: connect: Connection refused at /opt/xcat/lib/perl/xCAT/Client.pm line 248. " 
I want to use a persistant volume (outside docker container), i.e.  two different xcat instance can read the same database or if one instance dies the newer one is able to use all the previous data like mounted os images, set of create nodes and so on. 
Right now even if i have to run a new instance i need to delete the mounted volumes on docker host and then run the new instance.

**Comment by Obihoernchen** [comment]
Hi, unfortunately this xCAT docker container is using a very old version of xCAT and it is not maintained anymore.
Please use the official RPM/DEB based xCAT packages instead.

**Comment by DataSenseiAryan** [comment]
I don't think using the latest container would solve that. Anyway, I have solved it myself for my use case. Thanks for the reply.
